### PR TITLE
Base image support for CSM artifacts

### PR DESCRIPTION
**Pull request by eric-young**
# Description
Adds a base image, based upon RedHat UBI Micro, for Dell CSM artifacts to use as a base image. This centralizes and simplifies the management and updating of the image.

# Checklist:

- [X] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [n/a ] I have verified that new and existing unit tests pass locally with my changes
- [n/a] I have not allowed coverage numbers to degenerate
- [n/a] I have maintained at least 90% code coverage
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] I have maintained backward compatibility

### CODE REVIEW

**Comment by gallacher** [comment]
@eric-young, is there an opportunity to provide some information in the README file with some build usage instructions?

**Comment by eric-young** [comment]
> @eric-young, is there an opportunity to provide some information in the README file with some build usage instructions?

Done. Also added the ability to build as non-root users

**Review by gallacher — APPROVED** [review]

**Comment by gallacher** [comment]
> > @eric-young, is there an opportunity to provide some information in the README file with some build usage instructions?
> 
> Done. Also added the ability to build as non-root users

Thank you @eric-young!

**Comment by donatwork** [comment]
I see one error:

$ make docker
Building base image from registry.access.redhat.com/ubi9/ubi-micro@sha256:9dbba858e5c8821fbe1a36c376ba23b83ba00f100126f2073baa32df2c8e183a and loading dependencies...
cd base-image && ./build-base-image.sh -u "registry.access.redhat.com/ubi9/ubi-micro@sha256:9dbba858e5c8821fbe1a36c376ba23b83ba00f100126f2073baa32df2c8e183a" -t ""sample_registry""/""csm-base-image"":""test"" acl gnutls device-mapper-multipath e2fsprogs gnutls gzip hostname kmod libaio libblockdev libuuid libxcrypt-compat nettle nfs-utils nfs4-acl-tools numactl openssl rpm systemd tar util-linux which xfsprogs
Building base image from registry.access.redhat.com/ubi9/ubi-micro@sha256:9dbba858e5c8821fbe1a36c376ba23b83ba00f100126f2073baa32df2c8e183a
And creating sample_registry/csm-base-image:test
With packages of: acl gnutls device-mapper-multipath e2fsprogs gnutls gzip hostname kmod libaio libblockdev libuuid libxcrypt-compat nettle nfs-utils nfs4-acl-tools numactl openssl rpm systemd tar util-linux which xfsprogs
**Error: There are no enabled repositories in "/etc/yum.repos.d/".**
Unable to detect release version (use '--releasever' to specify release version)
0 files removed
47e4e5190bd5f42cd7d501edd90fd3ddb4eb3f23c6d6a0e314a1734d6fe11e89
Getting image source signatures
Copying blob 4092f1e3e312 skipped: already exists
Copying blob a7a506debb5f done   |
Copying config 71dc853854 done   |
Writing manifest to image destination
71dc853854514b6dfe4d1f2a79a900fd1ec48d6940891ca1b407dbe202171340
Built base image: sample_registry/csm-base-image:test

**Comment by eric-young** [comment]
> I see one error:
> 
> $ make docker Building base image from registry.access.redhat.com/ubi9/ubi-micro@sha256:9dbba858e5c8821fbe1a36c376ba23b83ba00f100126f2073baa32df2c8e183a and loading dependencies... cd base-image && ./build-base-image.sh -u "registry.access.redhat.com/ubi9/ubi-micro@sha256:9dbba858e5c8821fbe1a36c376ba23b83ba00f100126f2073baa32df2c8e183a" -t ""sample_registry""/""csm-base-image"":""test"" acl gnutls device-mapper-multipath e2fsprogs gnutls gzip hostname kmod libaio libblockdev libuuid libxcrypt-compat nettle nfs-utils nfs4-acl-tools numactl openssl rpm systemd tar util-linux which xfsprogs Building base image from registry.access.redhat.com/ubi9/ubi-micro@sha256:9dbba858e5c8821fbe1a36c376ba23b83ba00f100126f2073baa32df2c8e183a And creating sample_registry/csm-base-image:test With packages of: acl gnutls device-mapper-multipath e2fsprogs gnutls gzip hostname kmod libaio libblockdev libuuid libxcrypt-compat nettle nfs-utils nfs4-acl-tools numactl openssl rpm systemd tar util-linux which xfsprogs **Error: There are no enabled repositories in "/etc/yum.repos.d/".** Unable to detect release version (use '--releasever' to specify release version) 0 files removed 47e4e5190bd5f42cd7d501edd90fd3ddb4eb3f23c6d6a0e314a1734d6fe11e89 Getting image source signatures Copying blob 4092f1e3e312 skipped: already exists Copying blob a7a506debb5f done | Copying config 71dc853854 done | Writing manifest to image destination 71dc853854514b6dfe4d1f2a79a900fd1ec48d6940891ca1b407dbe202171340 Built base image: sample_registry/csm-base-image:test

This needs to run on RHEL, not openSuSE. I added a check to make sure that the user is on RHEL

**Review by donatwork — APPROVED** [review]

**Pull request merged**
