### PR TITLE
Updated user

### PR DESCRIPTION
**Pull request by jackieung-dell**
# Description
Updated a user on the CODEOWNERS file

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Review by abhi16394 — APPROVED** [review]

**Comment by atye** [comment]
My name appears twice in CODEOWNERS. Could that be fixed to once?

**Comment by jackieung-dell** [comment]
> My name appears twice in CODEOWNERS. Could that be fixed to once?

I only see your name once in the CODEOWNERS file Aaron.

**Comment by atye** [comment]
> > My name appears twice in CODEOWNERS. Could that be fixed to once?
> 
> I only see your name once in the CODEOWNERS file Aaron.

I see this:
image

**Comment by jackieung-dell** [comment]
> > > My name appears twice in CODEOWNERS. Could that be fixed to once?
> > 
> > 
> > I only see your name once in the CODEOWNERS file Aaron.
> 
> I see this: image

Ok, I removed the duplicate Github Username.

**Review by atye — APPROVED** [review]

**Pull request merged**
